const fakeData = [
  {
    id: 1,
    name: "Jacket",
    price: 120,
    category: "mens clothing",
    description: "Stylish denim jacket",
    image: "/jacket.jpg",
    alt: "alt",
  },
  {
    id: 2,
    name: "Shirt",
    price: 300,
    category: "women's clothing",
    description: "100% cashmere shirt",
    image: "/textiles.jpg",
    alt: "alt",
  },
  {
    id: 3,
    name: "Shoes",
    price: 200,
    category: "women's shoes",
    description: "Stylish shoes",
    image: "/womenshoes.jpg",
    alt: "alt",
  },
  {
    id: 4,
    name: "Ring",
    price: 250,
    category: "jewelry",
    description: "24k gold ri g",
    image: "/jewelry.jpg",
    alt: "alt",
  },
  {
    id: 5,
    name: "Dress",
    price: 60,
    category: "women's clothing",
    description: "100% lambswool dress",
    image: "/whitedress.jpg",
    alt: "alt",
  },
  {
    id: 6,
    name: "Pantsuit",
    price: 75,
    category: "women's clothing",
    description: "Wool and cashmere blanket",
    image: "/pantsuit.jpg",
    alt: "alt",
  },
];

export default fakeData;
