const fakeData = [
  {
    id: 1,
    name: "Jacket",
    price: 120,
    category: "mens clothing",
    description: "Stylish denim jacket",
    image: "/jacket.jpg",
    alt: "alt",
  },
  {
    id: 2,
    name: "Shirt",
    price: 300,
    category: "women's clothing",
    description: "100% cashmere shirt",
    image: "/jacket.jpg",
    alt: "alt",
  },
  {
    id: 3,
    name: "Sneakers",
    price: 200,
    category: "mens shoes",
    description: "Stylish sneakers",
    image: "/jacket.jpg",
    alt: "alt",
  },
  {
    id: 4,
    name: "Necklace",
    price: 250,
    category: "jewelry",
    description: "24k gold necklace",
    image: "/jacket.jpg",
    alt: "alt",
  },
  {
    id: 5,
    name: "Scarf",
    price: 60,
    category: "women's clothing",
    description: "100% lambswool scarf",
    image: "/jacket.jpg",
    alt: "alt",
  },
  {
    id: 6,
    name: "Blanket",
    price: 75,
    category: "household goods",
    description: "Wool and cashmere blanket",
    image: "/jacket.jpg",
    alt: "alt",
  },
];

export default fakeData;
